import type { WorkflowNode, WorkflowEdge } from "./workflow/types";
import { createDefaultChallengeConfig } from "./workflow/types";

export const EXAMPLE_WORKFLOWS = {
	basic: {
		nodes: [
			{
				id: "start-1",
				type: "Start" as const,
				title: "Inicio",
				description: "Punto de inicio del flujo",
				roles: ["Solicitante"],
				config: {},
				position: { x: 100, y: 200 },
				groupId: null,
			},
			{
				id: "form-1",
				type: "Form" as const,
				title: "Formulario de Solicitud",
				description: "Captura de datos del solicitante",
				roles: ["Solicitante"],
				config: { formId: "form-1" },
				position: { x: 400, y: 200 },
				groupId: null,
			},
			{
				id: "decision-1",
				type: "Decision" as const,
				title: "Validar Score",
				description: "Verificar puntaje crediticio",
				roles: ["Agente de Crédito"],
				config: { condition: "creditScore > 700" },
				position: { x: 700, y: 200 },
				groupId: null,
			},
			{
				id: "approve-1",
				type: "End" as const,
				title: "Fin",
				description: "Crédito aprobado",
				roles: ["Agente de Crédito"],
				config: {},
				position: { x: 1000, y: 100 },
				groupId: null,
			},
			{
				id: "reject-1",
				type: "Reject" as const,
				title: "Rechazado",
				description: "Crédito rechazado",
				roles: ["Agente de Crédito"],
				config: {},
				position: { x: 1000, y: 300 },
				groupId: null,
			},
		] as WorkflowNode[],
		edges: [
			{ id: "edge-1", from: "start-1", to: "form-1", label: null },
			{ id: "edge-2", from: "form-1", to: "decision-1", label: null },
			{ id: "edge-3", from: "decision-1", to: "approve-1", label: "Sí" },
			{ id: "edge-4", from: "decision-1", to: "reject-1", label: "No" },
		] as WorkflowEdge[],
	},
	api: {
		nodes: [
			{
				id: "start-2",
				type: "Start" as const,
				title: "Inicio",
				description: "",
				roles: ["Solicitante"],
				config: {},
				position: { x: 100, y: 250 },
				groupId: null,
			},
			{
				id: "form-2",
				type: "Form" as const,
				title: "Datos del Cliente",
				description: "",
				roles: ["Vendedor"],
				config: { formId: "form-1" },
				position: { x: 350, y: 250 },
				groupId: null,
			},
			{
				id: "api-1",
				type: "API" as const,
				title: "Consultar Buró",
				description: "Verificación externa",
				roles: ["Agente de Crédito"],
				config: { method: "POST", url: "https://api.buro.com/check" },
				position: { x: 600, y: 250 },
				groupId: null,
			},
			{
				id: "transform-1",
				type: "Transform" as const,
				title: "Calcular Score",
				description: "",
				roles: ["Agente de Crédito"],
				config: { code: "// Calcular score final" },
				position: { x: 850, y: 250 },
				groupId: null,
			},
			{
				id: "decision-2",
				type: "Decision" as const,
				title: "Evaluar Resultado",
				description: "",
				roles: ["Agente de Crédito"],
				config: { condition: "finalScore >= 650" },
				position: { x: 1100, y: 250 },
				groupId: null,
			},
			{
				id: "challenge-1",
				type: "Challenge" as const,
				title: "Aceptación de Términos",
				description: "El solicitante debe aceptar los términos y condiciones",
				roles: ["Solicitante"],
				config: {
					...createDefaultChallengeConfig("acceptance", {
						challengeTimeout: { value: 3, unit: "minutes" },
					}),
					deliveryMethod: "sms",
				},
				position: { x: 1350, y: 260 },
				groupId: null,
			},
			{
				id: "message-1",
				type: "Message" as const,
				title: "Notificar Aprobación",
				description: "",
				roles: ["Admin"],
				config: {
					channel: "email",
					template: "Felicidades, tu crédito fue aprobado",
				},
				position: { x: 1600, y: 150 },
				groupId: null,
			},
			{
				id: "approve-2",
				type: "End" as const,
				title: "Fin",
				description: "",
				roles: ["Agente de Crédito"],
				config: {},
				position: { x: 1600, y: 150 },
				groupId: null,
			},
			{
				id: "reject-2",
				type: "Reject" as const,
				title: "Rechazado",
				description: "",
				roles: ["Agente de Crédito"],
				config: {},
				position: { x: 1450, y: 360 },
				groupId: null,
			},
		] as WorkflowNode[],
		edges: [
			{ id: "edge-5", from: "start-2", to: "form-2", label: null },
			{ id: "edge-6", from: "form-2", to: "api-1", label: null },
			{ id: "edge-7", from: "api-1", to: "transform-1", label: null },
			{ id: "edge-8", from: "transform-1", to: "decision-2", label: null },
			{ id: "edge-9", from: "decision-2", to: "challenge-1", label: "Sí" },
			{ id: "edge-10", from: "challenge-1", to: "message-1", label: null },
			{ id: "edge-11", from: "message-1", to: "approve-2", label: null },
			{ id: "edge-12", from: "decision-2", to: "reject-2", label: "No" },
		] as WorkflowEdge[],
	},
	manual: {
		nodes: [
			{
				id: "start-3",
				type: "Start" as const,
				title: "Inicio",
				description: "",
				roles: ["Solicitante"],
				config: {},
				position: { x: 100, y: 200 },
				groupId: null,
			},
			{
				id: "form-3",
				type: "Form" as const,
				title: "Solicitud de Crédito",
				description: "",
				roles: ["Dealer"],
				config: { formId: "form-2" },
				position: { x: 400, y: 200 },
				groupId: null,
			},
			{
				id: "manual-1",
				type: "Decision" as const,
				title: "Revisión Manual",
				description: "Análisis por agente",
				roles: ["Agente de Crédito", "Admin"],
				config: { condition: "revisionCompleta" },
				position: { x: 700, y: 200 },
				groupId: null,
			},
			{
				id: "approve-3",
				type: "End" as const,
				title: "Fin",
				description: "",
				roles: ["Agente de Crédito"],
				config: {},
				position: { x: 1000, y: 100 },
				groupId: null,
			},
			{
				id: "reject-3",
				type: "Reject" as const,
				title: "Rechazado",
				description: "",
				roles: ["Agente de Crédito"],
				config: {},
				position: { x: 1000, y: 300 },
				groupId: null,
			},
		] as WorkflowNode[],
		edges: [
			{ id: "edge-12", from: "start-3", to: "form-3", label: null },
			{ id: "edge-13", from: "form-3", to: "manual-1", label: null },
			{ id: "edge-14", from: "manual-1", to: "approve-3", label: "Aprobar" },
			{ id: "edge-15", from: "manual-1", to: "reject-3", label: "Rechazar" },
		] as WorkflowEdge[],
	},
};
